version: '3.8'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./docker/mongo/data/
        target: /data/db
        read_only: false
    ports:
      - target: 27017
        published: 27018
    networks:
      - api

networks:
  api:
    driver: bridge
